"use client";
import { useInView } from "react-intersection-observer";
import { motion } from "framer-motion";
import Image from "next/image";
import bgChip from "@/images/collaborate/bgChip.png";
import ap_optimized from "@/images/collaborate/ap_optimized.png";

const Collaborate = () => {
  const [ref1, inView1] = useInView({
    triggerOnce: true,
    rootMargin: "-100px 0px",
  });
  const [ref2, inView2] = useInView({
    triggerOnce: true,
    rootMargin: "-110px 0px",
  });
  const [ref3, inView3] = useInView({
    triggerOnce: true,
    rootMargin: "-110px 0px",
  });
  return (
    <div className="w-full flex justify-center">
      <div className="w-full max-w-[1440px] md:py-[60px] md:px-[160px] py-[24px] px-[16px] flex flex-col items-center md:gap-[40px] gap-[16px]">
        <div className="w-full flex flex-col gap-[24px] items-center">
          <motion.div
            ref={ref1}
            initial={{ opacity: 0, y: 50 }}
            animate={{ opacity: inView1 ? 1 : 0, y: inView1 ? 0 : 50 }}
            transition={{ duration: 0.5 }}
            className="px-4 py-2 rounded-[40px] border border-[rgba(255,255,255,0.75)] bg-[rgba(255,250,209,0.04)] shadow-[0px_0px_12px_0px_#FFC872_inset] flex justify-center items-center"
          >
            <div className="md:text-[18px] leading-[24px] text-[16px] bg-[linear-gradient(90deg,#FFFCF5_-0.05%,#E5B865_37.73%,#F27969_82.63%)] bg-clip-text text-transparent">
              Building Today for the Future.
            </div>
          </motion.div>
          <motion.div
            ref={ref1}
            initial={{ opacity: 0, y: 50 }}
            animate={{ opacity: inView1 ? 1 : 0, y: inView1 ? 0 : 50 }}
            transition={{ duration: 0.5 }}
            className="w-full max-w-[500px] bg-[linear-gradient(91deg,#FFF-1.2%,#B0B1B4_99.77%)] md:text-[48px] text-[24px] leading-[32px] font-medium md:leading-[52px] tracking-[-1px] gradientSilver text-center"
          >
            Shard Chain is Coming
          </motion.div>
          <motion.div
            ref={ref1}
            initial={{ opacity: 0, y: 50 }}
            animate={{ opacity: inView1 ? 1 : 0, y: inView1 ? 0 : 50 }}
            transition={{ duration: 0.5 }}
            className="text-[rgba(255,255,255,0.66)] text-center md:text-[16px] md:leading-[22px] text-[14px] leading-[20px] font-light w-full max-w-[687px]"
          >
            Shard Chain is an AI-powered blockchain. We aim to position Shard
            Chain as an advanced AI Layer 1 for Crypto Mining and Decentralized
            Finance. All revenue generated by Shard AI will be distributed
            through Shard tokens and the Shard chain.
          </motion.div>
        </div>
        <div className="w-full md:px-[120px] md:flex gap-[16px]">
          <motion.div
            ref={ref2}
            initial={{ opacity: 0, y: 50 }}
            animate={{ opacity: inView2 ? 1 : 0, y: inView2 ? 0 : 50 }}
            transition={{ duration: 0.6 }}
            className="grow md:h-[612px] h-[300px] bg-[url('/images/collaborate/bgChip.png')] bg-cover rounded-[24px] overflow-hidden"
          ></motion.div>
          <motion.div
            ref={ref3}
            initial={{ opacity: 0, y: 50 }}
            animate={{ opacity: inView3 ? 1 : 0, y: inView3 ? 0 : 50 }}
            transition={{ duration: 0.6 }}
            className="w-full md:max-w-[363px] flex flex-col"
          >
            <div className="w-full p-[24px] flex flex-col gap-[24px] items-center">
              <div className="text-[#fff] text-[20px] font-medium leading-[28px]">
                Auto Rebasing
              </div>
              <div className="text-[rgba(255,255,255,0.66)] text-[14px] font-light leading-[22px] tracking-[0.2px] flex flex-col items-center">
                $cSHARD token is is natively rebasing on the Shard Chain: The
                yield for $cSHARD comes from mining protocol. $cSHARD can be
                redeemed for $cSHARD and stablecoin when bridging back to
                Ethereum. Smart contracts can opt-in to this rebasing, making it
                easy to existing Dapps to deploy on Shard Chain without any
                changes.
                <div className="w-[263px] h-[157px] relative">
                  <div className="w-[263px] h-[197px] absolute bottom-[-40px] left-0 ">
                    <Image
                      src={ap_optimized}
                      alt="ai optimized"
                      objectFit="cover"
                      layout="fill"
                    />
                  </div>
                </div>
              </div>
            </div>
          </motion.div>
        </div>
      </div>
    </div>
  );
};
export default Collaborate;
